import "./global.css";
import BodyStyleWrapper from "@/client/BodyStyleWrapper";
import ReactQueryWrapper from "@/client/ReactQueryWrapper";
import RecoilRootWrapper from "@/client/RecoilRootWrapper";
import StyledComponentsRegistry from "./registry";
import Translation from "@/client/Translation";

export const metadata = {
  title: 'SCHEDULE - SSR',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
          crossOrigin="anonymous"
          defer
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
          crossOrigin="anonymous"
          defer
        ></script>

        <script
          src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossOrigin="anonymous"
          defer
        ></script>

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <Translation locale="kr"/>
          <ReactQueryWrapper>
            <RecoilRootWrapper>
              <StyledComponentsRegistry>
                <BodyStyleWrapper>
                  {children}
                </BodyStyleWrapper>
              </StyledComponentsRegistry>
            </RecoilRootWrapper>
          </ReactQueryWrapper>
      </body>
    </html>
  );
}